/**
 * Token Authentication for Media Bridge
 * Uses HMAC-SHA256 for secure token verification with replay protection
 */

import { createHmac } from 'crypto';

interface TokenPayload {
  userId: string;
  agentId: string;
  callSid: string;
  exp: number;
  jti: string; // JWT ID for replay protection
}

interface VerifyResult {
  valid: boolean;
  payload?: TokenPayload;
  error?: string;
}

// Used JTIs (JWT IDs) for replay protection
const usedJtis = new Map<string, number>();

// Cleanup interval - runs every 5 minutes to remove expired JTIs
const CLEANUP_INTERVAL = 5 * 60 * 1000;
const JTI_EXPIRY = 10 * 60 * 1000; // 10 minutes

// Start cleanup timer (unref so it doesn't block process exit)
const cleanupTimer = setInterval(() => {
  const now = Date.now();
  for (const [jti, timestamp] of usedJtis) {
    if (now - timestamp > JTI_EXPIRY) {
      usedJtis.delete(jti);
    }
  }
}, CLEANUP_INTERVAL);
cleanupTimer.unref();

/**
 * UTF-8 safe base64url encoding
 */
function stringToBase64url(str: string): string {
  return Buffer.from(str, 'utf-8')
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

/**
 * UTF-8 safe base64url decoding
 */
function base64urlToString(str: string): string {
  // Restore base64 padding
  const padded = str + '==='.slice(0, (4 - (str.length % 4)) % 4);
  // Convert base64url to base64
  const base64 = padded.replace(/-/g, '+').replace(/_/g, '/');
  return Buffer.from(base64, 'base64').toString('utf-8');
}

/**
 * Generate HMAC-SHA256 signature
 */
function sign(data: string, secret: string): string {
  return createHmac('sha256', secret)
    .update(data)
    .digest('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');
}

/**
 * Verify a session token
 */
export function verifyToken(token: string, secret: string): VerifyResult {
  try {
    // Token format: payload.signature
    const parts = token.split('.');
    if (parts.length !== 2) {
      return { valid: false, error: 'Invalid token format' };
    }

    const [payloadB64, signature] = parts;

    // Verify signature
    const expectedSignature = sign(payloadB64, secret);
    if (signature !== expectedSignature) {
      return { valid: false, error: 'Invalid signature' };
    }

    // Decode payload
    const payloadJson = base64urlToString(payloadB64);
    const payload: TokenPayload = JSON.parse(payloadJson);

    // Check expiration
    if (Date.now() > payload.exp) {
      return { valid: false, error: 'Token expired' };
    }

    // Check replay protection (JTI)
    if (usedJtis.has(payload.jti)) {
      return { valid: false, error: 'Token already used (replay attack)' };
    }

    // Mark JTI as used
    usedJtis.set(payload.jti, Date.now());

    return { valid: true, payload };
  } catch (error) {
    return { valid: false, error: `Token verification failed: ${error}` };
  }
}

/**
 * Generate a session token (for testing purposes)
 * In production, tokens are generated by the Edge Function
 */
export function generateToken(
  userId: string,
  agentId: string,
  callSid: string,
  secret: string,
  expiryMs: number = 5 * 60 * 1000 // 5 minutes default
): string {
  const payload: TokenPayload = {
    userId,
    agentId,
    callSid,
    exp: Date.now() + expiryMs,
    jti: `${Date.now()}-${Math.random().toString(36).substring(2, 15)}`
  };

  const payloadB64 = stringToBase64url(JSON.stringify(payload));
  const signature = sign(payloadB64, secret);

  return `${payloadB64}.${signature}`;
}

/**
 * Check if a dev token is valid
 * Dev tokens bypass normal validation in development mode
 */
export function isValidDevToken(token: string, expectedDevToken: string): boolean {
  if (!expectedDevToken) return false;
  return token === expectedDevToken;
}

/**
 * Get the number of active JTIs (for monitoring)
 */
export function getActiveJtiCount(): number {
  return usedJtis.size;
}
